import { Geist, Geist_Mono } from "next/font/google";
import { LenisProvider } from "./components";
import "lenis/dist/lenis.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerBackgrounds = [
  "/home/headerBg.avif",
  "/app/headerBg.avif",
  "/servicios/headerBg.avif",
  "/faq/headerBg.avif",
  "/trabaja-con-nosotros/headerBg.avif",
];

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        {headerBackgrounds.map((href) => (
          <link key={href} rel="preload" as="image" href={href} fetchPriority="high" />
        ))}
      </head>
      <body>
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
